apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: producer-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: carapp.demo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: producer-helm
                port:
                  number: 8080