name: Deploy to AKS with Helm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Build and analyze with SonarQube
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn clean verify sonar:sonar \
          -Dsonar.projectKey=juanrafo_producer \
          -Dsonar.organization=juanrafo \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN

    - name: Build with Maven
      run: mvn clean package

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: az acr login --name ${{ secrets.ACR_NAME }}

    - name: Set image tag
      run: echo "IMAGE_TAG=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/producer:${{ env.IMAGE_TAG }} .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/producer:${{ env.IMAGE_TAG }}

    - name: Set AKS credentials
      run: az aks get-credentials --resource-group ${{ secrets.AKS_RG }} --name ${{ secrets.AKS_NAME }} --overwrite-existing

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Deploy with Helm (install or upgrade)
      run: |
        if helm status producer --namespace dev > /dev/null 2>&1; then
          echo "Release existe, haciendo upgrade..."
          helm upgrade --install producer ./helm \
            --set image.repository=${{ secrets.ACR_NAME }}.azurecr.io/producer \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --namespace dev
        else
          echo "Release no existe, haciendo install..."
          helm install producer ./helm \
            --set image.repository=${{ secrets.ACR_NAME }}.azurecr.io/producer \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --namespace dev
        fi